#%RAML 0.8
title: "Hawkeye"
version: "0.0.1"
baseUri: http://localhost:3000/api

protocols: [ HTTP ]

traits:
  - secured:
      headers:
        Authorization:
          description: |
            Used to send a valid OAuth 2 access token.
          example: Bearer
          type: string

/clients:
  get:
    is: [secured]
    description: |
      Retrieves a list of all client applications. Accepts a list of fields to include or exclude.

/connections:
  get:
    is: [secured]
    description: |
      Retrieves every connection matching the specified strategy. All connections are
      retrieved if no strategy is being specified. Accepts a list of fields to include
      or exclude in the resulting list of connection objects.
  post:
    is: [secured]
    description: |
      Creates a new connection according to the JSON object received in body
  put:
    is: [secured]
    description: |
      Retrieves a connection by its id.
  delete:
    is: [secured]
    description: |
      Deletes a connection and all its users.

/templates:
  get:
    is: [secured]
    description: |
      Retrieves the list of connection templates.
