var AUTH_BASE_URL       = "https://kyron.auth0.com";
var AUTH_CLIENT_ID      = "0bETHKnP8vHAHSKnG9sX4DaW14p7QOBr";
var AUTH_CONNECTION_API = "https://kyron.auth0.com/api/v2/connections";
var AUTH_TOKEN          = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ3ZUs4U1VkNVVFaUtGd0FkM1dPZ0pOSm9raWxmN3djMSIsInNjb3BlcyI6eyJjb25uZWN0aW9ucyI6eyJhY3Rpb25zIjpbInJlYWQiLCJjcmVhdGUiLCJkZWxldGUiLCJ1cGRhdGUiXX19LCJpYXQiOjE0NDYxNDg4MjksImp0aSI6IjMzMTIwNDUzNzMzNzEyNDE2OWY0NTM5MWI5MjUyNTRmIn0.6TNrz-C_5Y-PZwXat_IYslNqClaN-LeF9YXCO0ZZSRk';
